name: MacOS Build

on:
  schedule:
  - cron: '0 5 * * *'

  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Setup Go Environment
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
        check-latest: true
        cache: true
    
    - name: Build for Intel OSX
      run: |
        go build -v -o reddit-dl_amd64-osx cmd/reddit-dl/main.go
    
    - name: Build for M1 OSX
      run: |
        GOARCH=arm64 go build -v -o reddit-dl_arm64-osx cmd/reddit-dl/main.go
      
    - name: Archive Files
      run: tar -czvf reddit-dl_osx.tar.gz reddit-dl_{amd64,arm64}-osx
      
    - name: Release
      uses: softprops/action-gh-release@v0.1.15
      with:
        tag_name: 'build'
        files: |
          reddit-dl_osx.tar.gz
