name: Linux Build

on:
  schedule:
  - cron: '* 5 * * *'
  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Setup Go Environment
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
        check-latest: true
    
    - name: Update Go Dependencies
      run: |
        go get -u
      working-directory: cmd/reddit-dl/
    
    - name: Build for 64bit Linux
      run: |
        go build -v -o reddit-dl_amd64-linux cmd/reddit-dl/main.go
      #working-directory: cmd/reddit-dl/
    
    - name: Build for 32bit Linux
      run: |
        GOARCH=386 go build -v -o reddit-dl_i386-linux cmd/reddit-dl/main.go

      # working-directory: cmd/reddit-dl/
      
    - name: Zip Files
      run: tar -czvf reddit-dl_linux.tar.gz *
      # working-directory: cmd/reddit-dl/
      
    #- name: Release
      #uses: softprops/action-gh-release@v0.1.15
      #with:
        #tag_name: 'snapshot'
        #files: |
          #src/lex-linux.zip
